spring.application.name=backend

# Postgresql config
spring.datasource.url=jdbc:postgresql://localhost:5432/pretriage_db?options=-c%20timezone=America/Argentina/Buenos_Aires
spring.datasource.username=myuser
spring.datasource.password=how5are#you2
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# validos: (validate, update, create, create-drop, none)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# registro el link al servidor auth0 para oauth
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-bktuk8spi6fy0cal.us.auth0.com/

# habilito docker para tests de integración
spring.docker.compose.skip.in-tests=false

#auth0 params

auth0.client-id.machine-to-machine=${AUTH0_M2M_CLIENT_ID}
auth0.client-secret.machine-to-machine=${AUTH0_M2M_CLIENT_SECRET}
auth0.scope.machine-to-machine=${AUTH0_M2M_SCOPE}
auth0.base-path=https://dev-bktuk8spi6fy0cal.us.auth0.com
auth0.client-id.app=${AUTH0_APP_CLIENT_ID}

#google api params

google.api.key=${GOOGLE_MAPS_API_KEY}
google.places.base-url=https://places.googleapis.com/v1/places

# para ordenar las colas
#   7200 = 2*60*60 equivalente a dos horas
tiempo.estimado.atencion-triage.segundos=7200

#inyecto archivo con variables de entorno para desarrollo
spring.config.import=optional:file:.env[.properties]
