@startuml Diagrama de secuencia AdminHospital H0027

actor AdminHospital


alt crearSector
    AdminHospital -> Controller : POST /api/admin/hospital/{hospitalId}/configuracion/sectores

    AdminHospital <-- Controller : ok
end
alt eliminarSector
    AdminHospital -> Controller : DELETE /api/admin/hospital/{hospitalId}/configuracion/sectores

    AdminHospital <-- Controller : ok
end 
alt modificarSector
    AdminHospital -> Controller : PUT /api/admin/hospital/{hospitalId}/configuracion/sectores

    AdminHospital <-- Controller : ok
end
alt deshabilitar especialidad
AdminHospital -> Controller: DELETE /api/admin/hospitales/{hospitalId}/configuracion/especialidades/{especialidadId}

Controller -> HospitalConfiguracionService : deshabilitarEspecialidad(userId, especialidadId, hospitalId, sectorId)
HospitalConfiguracionService -> StaffAccessService : exiguirAdmin(userId, hospitalId)
HospitalConfiguracionService <-- StaffAccessService: UsuarioAuth
HospitalConfiguracionService -> HospitalConfiguracionService: hospital()
HospitalConfiguracionService -> HospitalConfiguracionService: especialidad()
HospitalConfiguracionService -> HospitalConfiguracionService: sector()
HospitalConfiguracionService -> RepoSalas: existsByHospitalIdAndEspecialidadIdAndSectorIdAndActivaTrue(hospitalId, especialidadId, sectorId)
alt existe
    HospitalConfiguracionService --> Controller: throw ConflictoDeEstadoException
else no existe
    HospitalConfiguracionService-> HospitalConfiguracionService: eliminarEspecialidad()
    HospitalConfiguracionService -> HospitalConfiguracionService: obtenerConfiguracionHospital()
end

Controller <-- HospitalConfiguracionService: ConfiguracionHospitalResponse(especialidades, salas, sectores)
AdminHospital <-- Controller :ConfiguracionHospitalResponse(especialidades, salas, sectores)
end
alt crear sala
AdminHospital -> Controller: POST /api/admin/hospitales/{hospitalId}/configuracion/salas

Controller -> HospitalConfiguracionService: crearSala(userId, hospitalId, sectorId, GuardarSalaRequest(nombre,especialidad))
HospitalConfiguracionService -> StaffAccessService : exiguirAdmin(userId, hospitalId)
HospitalConfiguracionService <-- StaffAccessService: UsuarioAuth
HospitalConfiguracionService -> HospitalConfiguracionService: hospital()
HospitalConfiguracionService -> HospitalConfiguracionService: especialidadHabilitada()
HospitalConfiguracionService -> HospitalConfiguracionService: sector()
HospitalConfiguracionService -> RepoSalas: existsByHospitalIdAndSectorIdAndNombreIgnoreCase(hospitalId, sectorId, nombre)

alt existe
    Controller <-- HospitalConfiguracionService: throw ConflictoDeEstadoException
else no existe
    HospitalConfiguracionService -> HospitalConfiguracionService: new Sala()
    HospitalConfiguracionService -> RepoSalas: save(Sala)
    HospitalConfiguracionService -> HospitalConfiguracionService: crearResponse()
end

Controller <-- HospitalConfiguracionService: SalaHospitalResponse
AdminHospital <-- Controller: SalaHospitalResponse
end
alt actualizar sala
AdminHospital -> Controller: PUT /api/admin/hospitales/{hospitalId}/configuracion/salas/{salaId}
Controller -> HospitalConfiguracionService: actualizarSala(userId, hospitalId,sectorId, salaId, GuardarSalaRequest(nombre,especialidad))
HospitalConfiguracionService -> StaffAccessService : exiguirAdmin(userId, hospitalId)
HospitalConfiguracionService <-- StaffAccessService: UsuarioAuth
HospitalConfiguracionService -> HospitalConfiguracionService: hospital()
HospitalConfiguracionService -> HospitalConfiguracionService: sala()
HospitalConfiguracionService -> HospitalConfiguracionService: sector()
HospitalConfiguracionService -> HospitalConfiguracionService: especialidadHabilitada()
HospitalConfiguracionService -> RepoSalas: existsByHospitalIdAndNombreIgnoreCaseAndSectorIdAndIdNot(hospitalId, nombreSala, sectorId, salaId)
alt existe
   Controller <-- HospitalConfiguracionService : throw new ConflictoDeEstadoException
else no existe
    HospitalConfiguracionService -> RepoSalas: update(Sala)
    HospitalConfiguracionService <-- RepoSalas: Sala
    HospitalConfiguracionService -> HospitalConfiguracionService: crearResponse()
end

Controller <-- HospitalConfiguracionService: SalaHospitalResponse
AdminHospital <-- Controller: SalaHospitalResponse
end
alt actualizar estado sala
AdminHospital -> Controller: PATCH /api/admin/hospitales/{hospitalId}/configuracion/salas/{salaId}/estado
Controller -> HospitalConfiguracionService: actualizarEstadoSala(userId, hospitalid, sectorId, salaId, ActualizarEstadoSalaRequest(activa))
HospitalConfiguracionService -> StaffAccessService : exiguirAdmin(userId, hospitalId)
HospitalConfiguracionService <-- StaffAccessService: UsuarioAuth
HospitalConfiguracionService -> HospitalConfiguracionService: hospital()
HospitalConfiguracionService -> HospitalConfiguracionService: sala()
HospitalConfiguracionService -> HospitalConfiguracionService: sector()
HospitalConfiguracionService -> HospitalConfiguracionService: esActivarSala(ActualizarEstadoSalaRequest)
alt si
    HospitalConfiguracionService -> HospitalConfiguracionService: especialidadHabilitada(hospital, especialidadId)
end
HospitalConfiguracionService -> RepoSalas: update(Sala)
HospitalConfiguracionService <-- RepoSalas: Sala
HospitalConfiguracionService -> HospitalConfiguracionService: crearResponse()

Controller <-- HospitalConfiguracionService: SalaHospitalResponse
AdminHospital <-- Controller: SalaHospitalResponse
end
@enduml

@startuml Diagrama de secuencia Paciente H0027
actor Paciente

group selecionar hospital
    Paciente -> Controller: GET /api/hospitales/cercanos
    

    Controller -> AtencionHospitalService: buscarHospitalesCercanos()

    Paciente <-- Controller: List<Hospital>

    Paciente -> Controller: POST /api/atencion/hospital
    
    Controller -> AtencionHospitalService: seleccionarHospital(userId, pacienteId, codigoEsp)
    
    AtencionHospitalService -> AtencionHospitalService: obtenerPaciente(userId)
    
    AtencionHospitalService -> AtencionHospitalService: obtenerEspecialidad(codigoEsp)
    AtencionHospitalService -> RepoConsultasMedicas: obtenerConsultaPaciente(paciente)
    AtencionHospitalService <-- RepoConsultasMedicas: Optional<ConsultaMedica>
    AtencionHospitalService -> Optional : isPresent
    
    alt Existe
        AtencionHospitalService -> Optional : get
        AtencionHospitalService <-- Optional: ConsultaMedica
    end
    alt noExiste
        AtencionHospitalService -> AtencionHospitalService : new ConsultaMedica

        AtencionHospitalService -> AsignacionSectorService : asignarSector(consultaMedica)
        AsignacionSectorService -> ConsultaMedica: getEspecialidad()
        AsignacionSectorService <-- ConsultaMedica: Especialidad
        AsignacionSectorService -> RepoSectores : findByEspecialidad(Especialidad)
        AsignacionSectorService <-- RepoSectores : List<Sector>
        AsignacionSectorService -> AsignacionSectorService : seleccionarSector()

        AtencionHospitalService <-- AsignacionSectorService: Sector(salas: List<Sala>)
    end

    AtencionHospitalService -> IngresoColaService : ingresar(consultaMedica, NivelDeGravedadDefault, Sector)
    
    IngresoColaService -> IngresoColaService: updateConsultaMedica()
    IngresoColaService -> RepoGestoresDeColas: findByHospitalIdAndEspecialidadIdAndSectorId()
    alt existe
        IngresoColaService <-- RepoGestoresDeColas: GestorDeCola
    end
    alt noExiste
        IngresoColaService -> IngresoColaService : verificarQueExiste(Sector)
        alt existe 

            IngresoColaService-> IngresoColaService : new GestorDeCola(Hospital,Especialidad, Sector)
        end
        alt noExiste
            IngresoColaService-> IngresoColaService: Throw new Error
        end
    end
    IngresoColaService-> GestorDeCola: agregarConsultaMedicaALaCola(ConsultaMedica)
    IngresoColaService -> RepoGestoresDeColas: save(gestor)

    IngresoColaService -> RepoEntradasCola :  findByConsultaMedicaId()

    alt existe
        IngresoColaService <-- RepoEntradasCola: EntradaCola
    end
    alt noExiste
        IngresoColaService -> IngresoColaService: new EntradaCola
    end
    IngresoColaService -> RepoEntradasCola: update

    AtencionHospitalService <-- IngresoColaService : OK
    
    Controller <-- AtencionHospitalService: OK
    
    Paciente <-- Controller: OK
    
    Paciente -> Controller: GET /api/atencion/hospital
    
    Controller -> AtencionHospitalService: obtenerHospitalSeleccionado(userId)
    
    AtencionHospitalService -> AtencionHospitalService : obtenerConsultaConHospitalSeleccionado(userId)
    AtencionHospitalService -> ConsultaMedica : getHospital()
    AtencionHospitalService <-- ConsultaMedica: Hospital
    AtencionHospitalService -> Hospital : getDireccion
    AtencionHospitalService <-- Hospital : Direccion
    AtencionHospitalService -> ConsultaMedica: getSector()
    AtencionHospitalService <-- ConsultaMedica: Sector(salas: List<Sala>)
    
    AtencionHospitalService -> AtencionHospitalService : armarResponse()
    AtencionHospitalService --> Controller : HospitalSeleccionado
    Controller --> Paciente : HospitalSeleccionado

end
@enduml


@startuml Diagrama de secuencia Medico H0027

actor Medico

Medico -> Controller: POST /api/medico/sesiones/{sesionId}/llamar-proximo

Controller -> AtencionMedicoService : llamarProximo(userId, sessionId)
AtencionMedicoService -> AtencionMedicoService: obtenerSesionActiva(sessionId, userId)
AtencionMedicoService -> RepoGestoresDeColas: findByHospitalIdAndEspecialidadIdAndSectorId()
AtencionMedicoService <-- RepoGestoresDeColas: GestorDeCola
AtencionMedicoService -> RepoEntradasDeCola: findFirstByGestorDeColaIdAndEstadoOrderByPrioridadDescOrdenRelativoAsc(gestorId, EN_COLA)
AtencionMedicoService <-- RepoEntradasDeCola: EntradaCola

AtencionMedicoService -> EntradaCola : getConsulta()
AtencionMedicoService <-- EntradaCola: ConsultaMedica
AtencionMedicoService -> AtencionMedicoService: armarDTO()

Controller <-- AtencionMedicoService : ConsultaLlamadaDTO(Paciente,Sala,EstadoConsulta,Prioridad,...)

Medico <-- Controller: ConsultaLlamadaDTO(Paciente,Sala,EstadoConsulta,Prioridad,...)

Medico -> Controller: POST /api/medico/sesiones
Controller-> AtencionMedicoService: iniciarSesion(userId, hospitalId, especialidadId, sectorId, salaId)
AtencionMedicoService ->AtencionMedicoService : obtenerMedico()
AtencionMedicoService ->AtencionMedicoService : hospital()
AtencionMedicoService ->AtencionMedicoService : especialidad()
AtencionMedicoService ->AtencionMedicoService : sala()
AtencionMedicoService ->AtencionMedicoService : sector()
AtencionMedicoService ->AtencionMedicoService : validarAsignacion()
AtencionMedicoService ->AtencionMedicoService : validarSala()
AtencionMedicoService ->AtencionMedicoService : validarRecursosDisponibles()
AtencionMedicoService ->AtencionMedicoService : new SesionAtencionMedica
AtencionMedicoService -> RepoSesionesAtencionMedica : save(SesionAtencionMedica)
AtencionMedicoService -> AtencionMedicoService: crearResponse()

Controller <-- AtencionMedicoService: SesionAtencionMedicaDTO
Medico <-- Controller: SesionAtencionMedicaDTO
@enduml

@startuml Diagrama de secuencia Recepcionista H0027

actor Recepcionista
Recepcionista -> Controller: POST /api/recepcion/sessiones
Recepcionista <-- Controller: Session

Recepcionista -> Controller: POST /api/recepcion/admisiones
Controller -> AdmisionRecepcionService: crearAdmision(userId, CrearAdmisionRecepcionRequest(nombre, apellido, ...))
AdmisionRecepcionService -> AdmisionRecepcionService: obtenerSesionActiva(userId, sesionId) 
AdmisionRecepcionService -> RepoPacientes: findByNumeroDocumentoOrUsuarioAuthNumeroDocumento(dni, dni)
alt existe
    AdmisionRecepcionService <-- RepoPacientes: Paciente
else noExiste
    AdmisionRecepcionService -> AdmisionRecepcionService: crearPacientePresencial(CrearAdmisionRecepcionRequest(nombre, apellido, ...), dni)
end
AdmisionRecepcionService -> AdmisionRecepcionService: validarSiExisteConsultaMedicaEnCurso()
alt existe
     AdmisionRecepcionService --> Controller: throw AtencionEnCursoException()
else noExiste
   AdmisionRecepcionService-> RepoEspecialidadesMedicas: findByCodigo(codigoEspecilidad)
   AdmisionRecepcionService<-- RepoEspecialidadesMedicas: EspecialidadMedica
   AdmisionRecepcionService-> AdmisionRecepcionService: validarEspecialidadDisponible(EspecialidadMedica)
   AdmisionRecepcionService -> AdmisionRecepcionService: new ConsultaMedica

    AtencionHospitalService -> AsignacionSectorService : asignarSector(consultaMedica)
    AsignacionSectorService -> ConsultaMedica: getEspecialidad()
    AsignacionSectorService <-- ConsultaMedica: Especialidad
    AsignacionSectorService -> RepoSectores : findByEspecialidad(Especialidad)
    AsignacionSectorService <-- RepoSectores : List<Sector>
    AsignacionSectorService -> AsignacionSectorService : seleccionarSector()
    AtencionHospitalService <-- AsignacionSectorService: Sector(salas: List<Sala>)

   AdmisionRecepcionService -> RepoConsultaMedica: save(ConsultaMedicaNueva)
   AdmisionRecepcionService <-- RepoConsultaMedica: ok
   AdmisionRecepcionService -> AdmisionRecepcionService: new AdmisionRecepcion
   AdmisionRecepcionService -> RepoAdmisionesRecepcion: save(AdmisionRecepcion)
   AdmisionRecepcionService <-- RepoAdmisionesRecepcion: ok
end

Controller <-- AdmisionRecepcionService: AdmisionRecepcionDTO(pacienteId, estadoAdmision, prioridad, tiempoEstimado)

Recepcionista <-- Controller: AdmisionRecepcion(pacienteId, estadoAdmision, prioridad, tiempoEstimado)

Recepcionista -> Controller: POST /api/recepcion/admisiones/{admisionId}/finalizar

Controller -> AdmisionRecepcionService : finalizar(userId, admisionId, formulario)
AdmisionRecepcionService -> AdmisionRecepcionService : obtenerAdmision(userId, admisionId)
AdmisionRecepcionService -> SesionAdmision: getConsultaMedica()
AdmisionRecepcionService <-- SesionAdmision: ConsultaMedica
AdmisionRecepcionService -> ConsultaMedica: getSector()
AdmisionRecepcionService <-- ConsultaMedica: Sector
AdmisionRecepcionService -> TriageFormularioService: clasificar(formulario)
alt exito
    AdmisionRecepcionService <-- TriageFormularioService: TriageResultDTO
else ProveedorIaException
    AdmisionRecepcionService -> TriageFormularioService: resultadoFallback()
    AdmisionRecepcionService <-- TriageFormularioService: TriageResultDTO 
end

AdmisionRecepcionService -> IngresoColaService: ingresar(consultaMedica, prioridad, sector)
AdmisionRecepcionService <-- IngresoColaService: TiempoEstimadoAtencionResponse
AdmisionRecepcionService -> AdmisionRecepcionService: armarDTO()

Controller <-- AdmisionRecepcionService: AdmisionRecepcionDTO(pacienteId, estadoAdmision, prioridad, tiempoEstimado)

Recepcionista <-- Controller: AdmisionRecepcionDTO(pacienteId, estadoAdmision, prioridad, tiempoEstimado)

Recepcionista -> Controller: POST /api/recepcion/admisiones/{admisionId}/cancelar
Recepcionista <-- Controller: AdmisionRecepcionDetalleDTO(pacienteId, estadoAdmision, prioridad, tiempoEstimado)


@enduml

@startuml Diagrama de clases H0027
class Sector {
    - especialidad: EspecialidadMedica
    - salas: Set<Sala>
    - hospital: Hospital
    - asignados: Set<Paciente>
    - nombreSector: String
}

class AsignacionSectorService {

    - asignarSector(ConsultaMedica): Sector

}
AsignacionSectorService --> Sector

class GestorDeCola {
    - hospital: Hospital
    - especialidad: EspecialidadMedica
    - consultasEnEspera: List<ConsultaMedica>
    - entradas: List<EntradaCola>
    - sector: Sector
}
GestorDeCola -> Sector

class Sala {

    - nombre: String
    - sector: Sector
}
Sector -> "*" Sala
Sala -> Sector

@enduml